apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: name-lookup-api
spec:
  template:
    spec:
      containers:
      - image: victorfonseca/name-lookup-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: BROKER_URL
          value: http://broker-ingress.knative-eventing.svc.cluster.local/default/name-meanings-broker
        readinessProbe:
          tcpSocket:
            port: 8080
