apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: name-lookup-api
spec:
  template:
    spec:
      containers:
        - image: victorfonseca/name-lookup-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
