apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-meaning-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-meaning-consumer
  template:
    metadata:
      labels:
        app: name-meaning-consumer
    spec:
      containers:
      - name: consumer
        image: victorfonseca/name-meaning-consumer:latest
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_QUEUE
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ_QUEUE
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
