apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    app: rabbitmq
type: Opaque
data:
  username: Z3Vlc3Q=  # Base64 encoded value for "guest"
  password: Z3Vlc3Q=  # Base64 encoded value for "guest"
